name: Deploy NestJS to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.19.2'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel using FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }} # Correct input name for the FTP server
          username: ${{ secrets.FTP_PASSWORD }} # Correct input name for the FTP username
          password: ${{ secrets.FTP_PASSWORD }} # Correct input name for the FTP password
          server-dir: ${{ secrets.FTP_PATH }}/ # Make sure this ends with a trailing slash
          local-dir: ./dist/ # Ensure this ends with a trailing slash (folder path)
          port: ${{ secrets.FTP_PORT }} # Optional: Use custom port, default is 21
